### ISSUE TITLE
npe2 cookiecutter notes

### ISSUE THREAD

**Issue by tlambert03** [napari/cookiecutter-napari-plugin#69]
hey @nclack

Taking a look through the npe2 cookiecutter, instead of a PR, just want to put some tasks here that we can tackle individually:

- [x] we shouldn't use `from numpy.typing import ArrayLike` in `_writer` for two reasons: first, it's only available in pretty new versions of numpy (I think 1.20+) and we didn't pin numpy in the users' setup.cfg.  Second, it's not an accurate type., layer data can come in many types.  We're trying to codify this with the [LayerDataProtocol](https://github.com/napari/napari/pull/3560), but i wouldn't use that either.  Just call it `typing.Any` for now.
- [ ] writers need more docstrings with clearer expectations about what they expect, and what they should do.  I know there's a link there, but it would be nice if the cookiecutter stood alone a bit more.
- [x] #71
    ```py
    def write_single_image(path: str, data: Any): ...
    # should be changed to
    def write_single_image(path: str, data: Any, meta: dict): ...
    ```
    and
    ```py
    def write_multiple(path: str, data: List[ArrayLike], layer_types: List[str]): ...
    # should be change to
    def write_multiple(path: str, List[FullLayerData]): ...
    ```
    The args are passed [here](https://github.com/tlambert03/npe2/blob/921f5f120aff16ddbdb1c2c7de4c236eb860fcc7/npe2/io_utils.py#L185) 
- [x] ... obviously, we should make the equivalent of the `hook_specifications.py` for npe2, so we have one authoritative place to look for all signatures expected by npe2. (See https://github.com/napari/npe2/pull/61)
- [x] #70
  ```yaml
    commands:
      - id: napari-foobar.get_reader
        python_name: napari_foobar._reader:napari_get_reader
        title: Open data with napari FooBar
      - id: napari-foobar.writer
        python_name: napari_foobar._reader:napari_get_reader
        title: Save data with napari FooBar
  ```
- [x] (This one is in main like this, but just noting this so I don't forget)...  in `_widget.py`, we should prefer `viewer: 'napari.viewer.Viewer'`over using the param named `napari_viewer`, and we should add at the top:
```py
if TYPE_CHECKING:
    import napari.viewer
    import napari.layers
```

- [ ] writer tests need improvement (possible others as well)
