### ISSUE TITLE
The `python_name` for command `napari-foobar.writer` is duplicated in the commands list

### ISSUE THREAD

**Issue by nclack** [napari/cookiecutter-napari-plugin#70]
```yaml
    commands:
      - id: napari-foobar.get_reader
        python_name: napari_foobar._reader:napari_get_reader
        title: Open data with napari FooBar
      - id: napari-foobar.writer
        python_name: napari_foobar._reader:napari_get_reader
        title: Save data with napari FooBar
  ```
